version: '3.8'

services:
  plex-viewer:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PLEX_URL=${PLEX_URL}
      - ALLOWED_LIBRARIES=Movies,TV Shows
      - REFRESH_INTERVAL=21600
      - TZ=UTC
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s