version: '3.8'

services:
  plex-viewer:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PLEXURL=${PLEXURL}
      - ALLOWED_LIBRARIES=Movies
      - REFRESH_INTERVAL=21600
      - TZ=UTC
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped